# Generated by Django 3.2.4 on 2021-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Anonymous', max_length=100)),
                ('comment_body', models.TextField()),
                ('is_sub_comment', models.BooleanField()),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
